version: '3'
services:
  web:
    build: .
    image: acme
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: acme
  test:
    image: acme
    volumes:
      - .:/app
    command: python manage.py test
