# Generated by Django 4.2.6 on 2023-10-14 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_rate_rate_increase_percent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coverage",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["code"]},
        ),
    ]
