# Generated by Django 4.2.6 on 2023-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_alter_coverage_options_alter_state_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rate",
            name="monthly_tax_percent",
        ),
        migrations.AddField(
            model_name="state",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
            preserve_default=False,
        ),
    ]
