# Generated by Django 4.2.6 on 2023-10-15 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_remove_rate_monthly_tax_percent_state_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="coverage",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="rate",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="state",
            name="is_deleted",
        ),
    ]
